/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol AFUISnippetDelegate <NSObject>
- (id)snippetControllerViewController:(id)arg1;
- (void)snippetController:(id)arg1 changeSizeTo:(struct CGSize)arg2;
- (void)snippetControllerRemoveView:(id)arg1;
- (void)snippetController:(id)arg1 sendGenericAceCommand:(id)arg2;
- (id)snippetController:(id)arg1 domainObjectForIdentifier:(id)arg2;
- (id)snippetControllerEffectiveBundleForCoreLocation:(id)arg1;
- (BOOL)snippetControllerIsDevicePasscodeLocked:(id)arg1;
@end

