/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@interface SBActivationView : UIView
{
    UIView *_backgroundView;
    int _mode;
}

- (id)initWithFrame:(struct CGRect)arg1 mode:(int)arg2;
- (int)mode;
- (void)dealloc;

@end

