/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView, UILabel;

@interface SBAlertImageView : UIView
{
    UIImageView *_imageView;
    UILabel *_labelView;
}

- (id)initWithFrame:(struct CGRect)arg1 errorString:(id)arg2;
- (void)dealloc;
- (void)layoutSubviews;

@end

