/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class UIView;

@interface SBAssistantAlertDisplay : SBAlertDisplay
{
    UIView *_assistantView;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (void)alertDisplayWillBecomeVisible;
- (void)alertDisplayBecameVisible;
@property(retain, nonatomic) UIView *assistantView; // @synthesize assistantView=_assistantView;

@end

