/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface SBAssistantGuideModel : NSObject
{
    NSMutableArray *_domains;
}

- (id)init;
- (void)dealloc;
- (void)_loadAllDomains;
@property(readonly) NSArray *allDomains; // @synthesize allDomains=_domains;

@end

