/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBAssistantMicImages : NSObject
{
}

+ (void)initialize;
+ (unsigned int)listeningImageCount;
+ (unsigned int)thinkingImageCount;
+ (unsigned int)fullImageCount;
+ (id)listeningImageAtIndex:(unsigned int)arg1;
+ (id)thinkingImageAtIndex:(unsigned int)arg1;
+ (id)fullImageAtIndex:(unsigned int)arg1;
+ (id)thinkingOnImage;

@end

