/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

@interface SBAssistantInitialQueryInstructionsController : UIViewController
{
    UIViewController *_parent;
}

- (void)dealloc;
- (void)loadView;
- (void)_doneButtonHit:(id)arg1;
@property(retain, nonatomic) UIViewController *parent; // @synthesize parent=_parent;

@end

