/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : SBAlertItem
{
    SUDescriptor *_descriptor;
}

- (id)initWithDescriptor:(id)arg1;
- (void)dealloc;
- (id)updateName;
- (void)activateSoftwareUpdateSettingsDisplay;
- (void)activateDisplayWithURL:(id)arg1;
- (BOOL)forcesModalAlertAppearance;
- (BOOL)shouldShowInLockScreen;
- (BOOL)dismissOnLock;
@property(readonly, nonatomic) SUDescriptor *descriptor; // @synthesize descriptor=_descriptor;

@end

