/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface SBBluetoothController : NSObject
{
    NSMutableArray *_devices;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)firstBTDeviceToReportBatteryLevel;
- (BOOL)canReportBatteryLevel;
- (int)batteryLevel;
- (void)noteDevicesChanged;
- (void)startWatchingForDevices;
- (void)stopWatchingForDevices;
- (void)iapDeviceChanged:(id)arg1;
- (void)addDeviceNotification:(id)arg1;
- (void)removeDeviceNotification:(id)arg1;
- (void)connectionChanged:(id)arg1;
- (void)batteryChanged:(id)arg1;
- (void)updateBattery;
- (id)deviceForAudioRoute:(id)arg1;
- (BOOL)tetheringConnected;

@end

