/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBPhraseInterpretation.h"

@class NSString;

@interface SBConstantInterpretation : SBPhraseInterpretation
{
    NSString *_string;
}

- (id)initWithString:(id)arg1;
- (void)dealloc;
- (id)text;

@end

