/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBDeviceLockViewWithKeypad.h"

@class UIView;

@interface SBDeviceLockViewWithKeypadWildcat : SBDeviceLockViewWithKeypad
{
    UIView *_bottomContainer;
}

- (id)_initWithStyle:(int)arg1 interfaceOrientation:(int)arg2 showsEmergencyCall:(BOOL)arg3;
- (void)dealloc;
- (id)keypadView;

@end

