/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIKeyboard.h"

@class SBDeviceLockViewWithKeyboard;

@interface SBDeviceLockKeyboard : UIKeyboard
{
    SBDeviceLockViewWithKeyboard *_deviceLockView;
}

- (id)initWithFrame:(struct CGRect)arg1 deviceLockView:(id)arg2;
- (BOOL)canDismiss;
- (void)minimize;
- (void)maximize;
- (void)setMinimized:(BOOL)arg1;
- (BOOL)isMinimized;

@end

