/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay
{
}

- (void)useEmergencyCallButton;
- (void)deviceUnlockSucceeded;
- (void)deviceUnlockCanceled;
- (void)alertDisplayWillBecomeVisible;
- (void)dismiss;
- (float)delayForOthersActivation;
- (float)durationForOthersActivation;

@end

