/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIcon.h"

@interface SBIcon (Internal)
- (void)_notifyImageDidUpdate;
- (void)_notifyAccessoriesDidUpdate;
- (void)_notifyLaunchEnabledDidChange;
@end

