/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconLabel.h"

@interface SBNewsstandIconLabel : SBIconLabel
{
}

- (id)_textColor;
- (id)_textShadowColor;
- (struct CGSize)_textShadowOffset;
- (id)_textFont;

@end

