/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBFolderIconView.h"

@interface SBNewsstandIconView : SBFolderIconView
{
}

- (id)_folderBackgroundImage;
- (id)_folderForegroundImage;
- (void)setIconScrollPosition:(int)arg1 animated:(BOOL)arg2;
- (void)_positionMiniGrid;
- (void)positionIconImageView;
- (void)placeIconOverlayView;

@end

