/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableView.h"

@class UIView;

@interface SBNewsstandShelfTableView : UITableView
{
    UIView *_backView;
}

- (void)didAddSubview:(id)arg1;
- (void)willRemoveSubview:(id)arg1;
- (void)reloadData;
@property(nonatomic) UIView *shelfFrameView; // @synthesize shelfFrameView=_backView;

@end

