/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIcon.h"

@interface SBNullIcon : SBIcon
{
}

+ (id)nullIcon;
- (id)generateIconImage:(int)arg1;
- (BOOL)shouldCacheImageForFormat:(int)arg1;

@end

