/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBWaveView.h"

@interface SBPathWaveView : SBWaveView
{
}

+ (Class)layerClass;
- (id)_shapeLayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (struct CGPath *)_copyCurrentPath;
- (void)_updateCurrentPath;
- (void)setColor:(id)arg1;
- (void)layoutSubviews;

@end

