/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class SAAceView;

@interface SBPendingAceView : NSObject
{
    SAAceView *_aceView;
    int _phase;
}

- (id)initWithAceView:(id)arg1 phase:(int)arg2;
- (void)dealloc;
@property(nonatomic) int phase; // @synthesize phase=_phase;
@property(retain, nonatomic) SAAceView *aceView; // @synthesize aceView=_aceView;

@end

