/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@interface SBPrintStatusIcon : SBLeafIcon
{
}

- (id)generateIconImage:(int)arg1;
- (id)displayName;
- (id)leafIdentifier;
- (BOOL)shouldEllipsizeLabel;
- (id)applicationBundleID;
- (BOOL)delaysUnhighlightWhenTapped;

@end

