/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBPhraseInterpretation.h"

@class NSArray;

@interface SBSpeechTokenInterpretation : SBPhraseInterpretation
{
    NSArray *_speechTokens;
}

- (id)initWithSpeechTokens:(id)arg1;
- (BOOL)removeSpaceBefore;
- (BOOL)removeSpaceAfter;
- (void)dealloc;
- (id)text;

@end

