/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface SBTransientSettings : NSObject
{
    NSMutableDictionary *_transientSettings;
    BOOL _dirty;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)reload;
- (void)save;
- (id)_path;
- (void)_load;

@end

