/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class UIWebClip;

@interface SBWebApplicationIcon : SBApplicationIcon
{
    UIWebClip *_webClip;
}

- (id)initWithApplication:(id)arg1;
- (void)dealloc;
- (id)_urlForLaunch;
- (void)launch;
- (void)launchFromViewSwitcher;
- (id)generateIconImage:(int)arg1;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)allowsUninstall;
- (void)completeUninstall;
- (id)uninstallAlertTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertCancelTitle;
- (id)webClip;
- (id)folderTitleOptions;
- (id)folderFallbackTitle;
- (BOOL)canGenerateGhostlyImageInBackground;

@end

